name: 'Setup localstack service'
description: 'Download & run localstack container'
inputs:
  # inputs for https://github.com/docker/login-action
  username:
    description: 'Username used to log against the github registry'
    required: false
    default: ${{ github.actor }}
  password:
    description: 'Password or personal access token used to log against the github registry'
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - shell: bash
      run: |
            pip install localstack==2.3.2                                # Install LocalStack cli
            # Below image was copied manually from localstack/localstack:2.2 and uploaded to ghcr
            docker pull localstack/localstack@sha256:1a1089d01cb8a16e72dd9f30a29a65d5310805b54b40ecf26cf3803a7690053d     # Make sure to pull a working version of the image
            PROVIDER_OVERRIDE_S3=v3 localstack start -d                                          # Start LocalStack in the background

            echo "Waiting for LocalStack startup..."                     # Wait 30 seconds for the LocalStack container
            localstack wait -t 30                                        # to become ready before timing out
            echo "Startup complete"

            aws --endpoint-url=http://localhost:4566 s3api create-bucket --bucket zot-storage --region us-east-2 --create-bucket-configuration="{\"LocationConstraint\": \"us-east-2\"}"
      env:
        AWS_ACCESS_KEY_ID: fake
        AWS_SECRET_ACCESS_KEY: fake
        

