on: [push, pull_request]
name: Build and test ZOT
jobs:
  build-test:
    name: Build and test ZOT
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Install dependencies
        run: |
          go get -u github.com/swaggo/swag/cmd/swag
          go mod download
          sudo apt-get update
          sudo apt-get install rpm
          sudo apt install snapd
          sudo snap install skopeo --edge --devmode

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Run build and test
        run: make

      - name: Upload code coverage
        uses: codecov/codecov-action@v1  
  upload_artifacts:
    name: Upload Artifacts
    needs: [create_release]
    runs-on: ubuntu-latest
    steps:
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create_release.outputs.id }}
          args: 'bin/zot*'


      