name: 'Sync golang image from docker to ghcr'
on:
  workflow_dispatch:
    inputs:
      golang_version:
        required: true
        description: The version of golang to push to ghcr.io/project-zot/*.
        type: string

env:
  GOLANG_VERSION: ${{ github.event.inputs.golang_version }}

jobs:
  sync-golang:
    name: 'pull & push golang'
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Tag and push to ghcr
        run: |
          docker pull golang:${{ env.GOLANG_VERSION }}
          docker tag golang:${{ env.GOLANG_VERSION }} ghcr.io/${{ github.repository_owner }}/golang:${{ env.GOLANG_VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/golang:${{ env.GOLANG_VERSION }}
